Write a program to store the values of the matrix given below in a 2D list.
Then calculate
1. The sum of the diagonal elements
2. The sum of all elements above the diagonal and the sum of all the elements below the diagonal
3. The sum of all the numbers in the rows of the matrix
4. The sum of all the columns of the matrix
5. Find out the max and min element of each column.
<br/><br/>
a = [[2 3 4]
     [1 5 6]
     [5 8 5]]

**Creating the list/ array**

In [4]:
# importing the numpy module
import numpy as np

In [8]:
# storing the matrix in a numpy array
matrix = np.array([2,3,4,1,5,6,5,8,5])
# reshaping the array into a 3x3 array
matrix = matrix.reshape(3,3)

In [10]:
# The array must be of shape 3x3
print(matrix)

[[2 3 4]
 [1 5 6]
 [5 8 5]]


**Question 1**

_Finding the sum of all diagonal elements by iterating theough the matrix_

In [28]:
sum = 0 # this variable will store the sum

for row in range(len(matrix)):
    for column in range(len(matrix[row])):
        if row == column:
            sum += matrix[row][column]

In [29]:
print(sum) # checking the result

12


_Finding the sum of all diagonal elements by using ndenumerate and checking diaginal indices_

In [30]:
sum2 = 0 # this variable will store the sum
for index, element in np.ndenumerate(matrix):
    """
        the index variable will store a tuple which contains
        the 2D index of the element, which is stored in the 
        variable element
    """
    if (index[0] == index[1]):
        sum2 += element
        

In [31]:
print(sum2)

12


**Question 2**

In [35]:
# using ndenumerate to iterate through the 2D array
sum_of_elements_above, sum_of_elements_below = 0, 0
for index, element in np.ndenumerate(matrix):
    # checking if the element lies above the diagonal [row < column]
    if index[0] < index[1]:
        sum_of_elements_above += element
    # checking if the element lies below the diagonal [row > column]
    elif index[0] > index[1]:
        sum_of_elements_below += element
        

In [37]:
print (f'The sum of elements above the diagonals is: {sum_of_elements_above}\nThe sum of elements below the diagonal is: {sum_of_elements_below}')

The sum of elements above the diagonals is: 13
The sum of elements below the diagonal is: 14
